[package]
name = "my-project"
version = "0.1.0"
authors = ["runner"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.9"
rand = "0.8.5"
rand_core = "0.6.4"
rand_distr = "0.4.3"
rand_pcg = "0.3.1"
